#!/usr/bin/env node

require('shelljs/global')
const chalk = require('chalk')
const arg = process.argv
const param = arg[2]
const param2 = arg[3]
const lg = console.log

if(param === 'ls') {
    let _files = ''
    ls('src/model').forEach(file => {
        _files += `${chalk.bgYellow('['+file+' Model] ')} `
    })
    lg(chalk.bold.black(_files))
} else if(param === 'init') {
    if(param2 === undefined) exit(1)
    let _d = `dev:${param2}`
    let _b = `build:${param2}`
    sed('-i', new RegExp(/dev:(\w+)?/), _d, 'package.json')
    sed('-i', new RegExp(/build:(\w+)?/), _b, 'package.json')
    let _d2 = chalk.red(` yarn ${_d} `)
    let _b2 = chalk.red(` yarn ${_b} `)
    lg(`${chalk.bgBlack(_d2)}${chalk.bgBlue(' '+param2+' Model => Start Server! ')}`)
    lg(`${chalk.bgBlack(_b2)}${chalk.bgBlue(' '+param2+' Model => Build Project! ')}`)
} else {
    exit(1)
}